package com.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubMetaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubMetaAllPropertiesEquals(SubMeta expected, SubMeta actual) {
        assertSubMetaAutoGeneratedPropertiesEquals(expected, actual);
        assertSubMetaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubMetaAllUpdatablePropertiesEquals(SubMeta expected, SubMeta actual) {
        assertSubMetaUpdatableFieldsEquals(expected, actual);
        assertSubMetaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubMetaAutoGeneratedPropertiesEquals(SubMeta expected, SubMeta actual) {
        assertThat(actual)
            .as("Verify SubMeta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubMetaUpdatableFieldsEquals(SubMeta expected, SubMeta actual) {
        assertThat(actual)
            .as("Verify SubMeta relevant properties")
            .satisfies(a -> assertThat(a.getDescricao()).as("check descricao").isEqualTo(expected.getDescricao()))
            .satisfies(a -> assertThat(a.getConcluida()).as("check concluida").isEqualTo(expected.getConcluida()))
            .satisfies(a -> assertThat(a.getDataLimite()).as("check dataLimite").isEqualTo(expected.getDataLimite()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubMetaUpdatableRelationshipsEquals(SubMeta expected, SubMeta actual) {
        assertThat(actual)
            .as("Verify SubMeta relationships")
            .satisfies(a -> assertThat(a.getMeta()).as("check meta").isEqualTo(expected.getMeta()));
    }
}
